- .github/PULL_REQUEST_TEMPLATE.md
This file has the minimum required information to create a pull request in this repository.
Closes #2 
> Add pull request template file

- .github/workflows/CI.yml
Add a linting check to the GitHub workflows.
Closes #8 
- [NA] Lint is passing
> Add linting to workflows

- README.dev.md
This file has the developers' guide for contributions to this repository.
Closes #1 
- [NA] Lint is passing
> Add README file for developers

- .github/workflows/StaleWorkflow.yml
Added Staleworkflow yaml file that will autolabel issues and PRs as stale after a specified amount of time. Will run automatically every day
Closes #23
> Added StaleWorkflow yaml

- docs/make.jl
- docs/src/api.md
- docs/src/how-to-use.md
- docs/src/index.md
- docs/src/mathematical-formulation.md
- docs/src/reference.md
- docs/src/tutorial.md
The files have the documentation structure and the model's mathematical formulation.
Closes #12
Closes #15
- [NA] Lint is passing
> Add files and changes for the documentation

- .github/workflows/CI.yml
- .github/workflows/CompatHelper.yml
- .github/workflows/StaleWorkflow.yml
- .github/workflows/TagBot.yml
- .markdownlint.json
- .pre-commit-config.yaml
- .yamllint.yml
Adds yamllint and prettier to pre-commit.
Adds a configuration file for yamllint.
Adds 4 spaces indentation option to `pretty-format-json`.
Fix all yaml and json files using those options.
Closes #40 
> Add more linters and formatters for yaml and json

- .github/ISSUE_TEMPLATE/ADDITION-REQUEST.yml
- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/IMPROVEMENT-REQUEST.yml
This PR updates the YML files format in the ISSUE_TEMPLATES folder
Closes #51
> update format of YML issue templates

- .github/workflows/Docs.yml
- Project.toml
- README.dev.md
- README.md
- benchmark/Project.toml
- benchmark/benchmarks.jl
- docs/Project.toml
- docs/make.jl
- docs/src/how-to-use.md
- docs/src/index.md
- docs/src/reference.md
- src/TulipaEnergyModel.jl
- test/runtests.jl
Change the model name to Tulipa Energy Model
Closes #60
> Change model name

- README.dev.md
Add the most commonly used Git commons in README.dev.md.
Closes #43 
#41 
> Add git commands in README.dev

- benchmark/benchmarks.jl
- src/io.jl
- test/runtests.jl
Use the CSV and DataFrames packages to write the output file instead of manually writing each line.
Closes #14 
> Use DataFrames to write to csv

- .github/workflows/Benchmark.yml
- .github/workflows/Docs.yml
- .github/workflows/Lint.yml
- .github/workflows/Stale.yml
- .github/workflows/Test.yml
Explicitly list the permissions of each workflow
Closes #65 
> Explicitly list the permissions of each workflow

- README.md
Complete the README file with the basic information for release
Closes #10
> Complete README file

- README.dev.md
Renamed TulipaBulb to TulipaEnergyModel in README.dev.md line ending instructions
Closes #85
> Rename TulipaBulb in README.dev.md

- src/io.jl
- src/model.jl
- test/runtests.jl
Use the `test/input/tiny` data.
Update the io function to use node instead of asset in the columns.
Compute the edge list from the graph.
Closes #108 
> Use new tiny data and the graph structure in the model

- docs/src/how-to-use.md
- docs/src/mathematical-formulation.md
Changed HowTo and added link to Preprint
Closes #141
> Changed HowTo and added link to Preprint

- src/io.jl
Created new function that reads CSVs into DataFrames.
Made it into a separate function. That function is still called multiple times, so I don't know if we want to build into the function that it does all of the files and dfs at once.
Closes #104 
> Made reading CSV into dataframe a separate function

- test/runtests.jl
Added new test that includes non-silent validation check
Closes #145
> Added new test to achieve full coverage

- README.dev.md
- benchmark/benchmarks.jl
- src/model.jl
- test/runtests.jl
- Split `optimise_investment` function into two functions, `create_model` and `solve model`
- Change benchmark.jl to only include `create_model`
- Change runtests.jl 
- Minor edits to complete the instructions for running benchmark locally in README.dev.md
Closes #153 
> Separate create and solve model

- README.dev.md
Added -u to git push myfork branch
Added myfork branch to git push --force (for rebase)
Closes #158
> Added details to README.dev to prevent pushing to origin

- README.dev.md
Added JuliaFormatter install instructions
Closes #186
> Updated README.DEV to include JuilaFormatter

- benchmark/benchmarks.jl
Changed names of input and output folders for benchmark so fix Warnings.
Closes #174
> Fixed benchmark "redefinition of constant" warning

- .github/ISSUE_TEMPLATE/ADDITION-REQUEST.yml
- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/IMPROVEMENT-REQUEST.yml
Updated issue templates so they're simpler to fill in
Closes #90
> Updated issue templates

- src/input_tables.jl
- test/inputs/Norse/rep-periods-data.csv
- test/inputs/tiny/rep-periods-data.csv
Add new columns to the Norse and tiny rp files.
Update input_tables RepPeriodData schema.
Closes #179 
> Add new columns to the rp file

- src/io.jl
- src/model.jl
- test/inputs/Norse/rep-periods-data.csv
- Change the definition of K, so that is a dict with rp as the keys
- In the main model, index K accordingly
Closes #180 
> 180 make k dependent on rp

- test/test-case-studies.jl
Updated warning catch to (hopefully) work with Julia 1.6
Closes #190
> Fix infeasible catch for Julia 1.6

- test/inputs/Norse/flows-data.csv
Changed node_id to asset_name to match Tiny
Closes #203
> Changed Norse flows-data to use asset_name

- .github/workflows/TestOnPR.yml
Also test on Julia 1.6 on PRs
Closes #133
> Also test on Julia 1.6 on PRs

- src/input-tables.jl
- src/io.jl
- test/inputs/Norse/assets-time-intervals.csv
- test/inputs/Norse/flows-time-intervals.csv
- test/inputs/Tiny/assets-time-intervals.csv
- test/inputs/Tiny/flows-time-intervals.csv
- test/test-io.jl
Add files with Assets and Flows time intervals and functions to parse it.
Closes:
- #182 
> Add files with Assets and Flows time intervals and functions to parse it

- README.dev.md
New section in the README.dev to build and see the documentation locally.
Closes #207 
> Add a section to build docs locally

- README.dev.md
> Add LocalCoverage instructions to README.dev.md

- src/model.jl
Create expressions for incoming and outgoing flows, with and without efficiency.
Closes #222 
> Create expressions for incoming and outgoing flows

- .github/workflows/Benchmark.yml
When we write `/run-benchmark`, the action will write "Running benchmark...". And after it is done, it will delete that comment.
Closes #233 
> Write a comment on the PR when running benchmark

- .github/workflows/Benchmark.yml
Small fix on the comment line.
Can't be tested before merged.
Closes #243 
> Add quotes on the benchmark comment body

- src/TulipaEnergyModel.jl
- src/run-scenario.jl
- test/test-case-studies.jl
Added a function to run Tulipa in one line.
Has two modules depending on input:
run_scenario(input_folder,output_folder)
run_scenario(scenario_name)
Definitely needs some work and testing before merging.
Closes #209
> Added function to run Tulipa in one line

- Project.toml
Because it is required for registration now.
> Add compat bounds to SparseArrays

- .gitignore
Added coverage/ folder to gitignore so that files created by local coverage are ignored
Closes #245
> Added coverage to gitignore

- src/model.jl
Filter the partitions that intersect in the for definition, to avoid summing zeros.
Should be faster since it is strictly less work, but I am curious to know how much faster.
Closes #220 
> Manually filter the partitions that intersect

- .JuliaFormatter.toml
- docs/make.jl
- src/io.jl
- src/model.jl
- test/test-io.jl
- test/test-time-resolution.jl
Closes nothing. Part of #254 discussion.
> Increase .JuliaFormatter margin to 100

- src/graph-structure.jl
- src/io.jl
- src/model.jl
Add a field `profiles` to the assets and flows structs.
Remove the profiles from the parameters.
Use these profiles in the model.
Closes #261 
> Add profiles to graph structure

- src/graph-structure.jl
- src/io.jl
- src/model.jl
- test/test-io.jl
Move the assets and flows partitions to inside the graph structure.
Closes #271 
> Move partitions to inside the graph structure

- benchmark/benchmarks.jl
- src/TulipaEnergyModel.jl
- src/io.jl
- src/model.jl
- src/run-scenario.jl
- src/structures.jl
- test/test-case-studies.jl
- test/test-io.jl
Create a structure for representative periods.
Move the constraints partition to the model creation.
Closes #262 
> Create a structure for representative periods

- benchmark/benchmarks.jl
- src/input-tables.jl
- src/io.jl
- src/model.jl
- src/run-scenario.jl
- src/structures.jl
- test/test-case-studies.jl
Create EnergyModel structure to hold all parts of the problem.
For now, it is not very useful, since it just changes two parameters to one.
After #246 and #268, it will include more parts.
If preferred, I can delay this PR until then.
Closes #263 
> Create EnergyModel structure

- CITATION.cff
Added Lauren's ORCID number to CFF
Closes #258
> Added Lauren's ORCID to CFF

- src/model.jl
- src/structures.jl
- src/time-resolution.jl
Move the constraints partitions to EnergyProblem.
Closes #279 
> Move the constraints partitions to EnergyProblem

- src/model.jl
- test/test-case-studies.jl
Add the duration of the flow to the calculation of the variable cost in the objective function.
Closes #300 
> Fix objective function calculation of the variable cost

- README.dev.md
- benchmark/profiling.jl
Add a file with profiling commands.
Add instruction to the README.dev.md on how to profile.
Part of #294.
> Add profiling.jl and instructions

- .markdown-link-check.json
- .pre-commit-config.yaml
- docs/Project.toml
- docs/src/how-to-use.md
- docs/src/tutorial.md
Create some documentation.
Describe structures.
Describe input.
Show basic usage from beginning to end.
Show some graph usage examples.
Show solution usage examples.
Closes #324 
> Document structures, how to use, and tutorial

- .github/workflows/Docs.yml
- docs/Project.toml
- docs/src/tutorial.md
Add simple examples of writing to CSV and plotting.
Closes #327
> Short tutorial on writing to a CSV and plots

- benchmark/benchmarks.jl
> Small fix on benchmarks

- src/model.jl
Filter the expression like the other expression.
Closes #332 
> Filter B_flow in the highest resolution expressions

- docs/make.jl
- docs/src/api.md
- docs/src/how-to-use.md
- docs/src/index.md
- docs/src/reference.md
> Made documentation cleaner and more navigable

- src/io.jl
Instead, loop over all values.
**This needs manual verification**
> Avoid creating a dataframe of unique values in IO

- src/run-scenario.jl
> Reduced run_scenario from 2 functions to 1 with same functionality

- Project.toml
> Release 0.5.1

- src/run-scenario.jl
- test/test-case-studies.jl
Added verbose option so it can be used in create_model function
Closes #309 
> Add verbose option to run_scenario

- benchmark/EU/rep-periods-data.csv
- benchmark/EU/rep-periods-mapping.csv
- test/runtests.jl
The EU data was not updated. I hope what I have here is the correct new file.
I have also added a call at the end of the tests to ensure that the EU data can be loaded. This should avoid errors like this in the future.
Closes #364 
> Update EU data with rep-periods-data.csv

- src/solve-model.jl
- test/Project.toml
- test/runtests.jl
- test/test-case-studies.jl
Remove SCIP.
Test Norse with Cbc and GLPK as well.
Closes #378 
> Test Norse with Cbc and GLPK and conditionally with SCIP

- README.md
Add stable doc badge
Closes #385 
> Add stable doc badge

- Project.toml
- src/TulipaEnergyModel.jl
- src/plot.jl
- test/test-case-studies.jl
Created three new functions for basic plotting:
- One flow over one RP
- Total capacity (initial + investment) of assets
- Final asset and flow capacities in the graph
I did not include tests of these functions. They could probably also use more helpful error messages if they're misused.
Closes #191 
> 191 plot functions

- docs/src/how-to-use.md
- src/create-model.jl
- src/input-tables.jl
- src/structures.jl
- test/inputs/Norse/assets-data.csv
- test/test-case-studies.jl
Include the option to allow missing values in the initial storage level to consider having it as a free value only depending on the last time block.
Closes #296 
> Add option to have the initial storage level as free value

- .github/workflows/Benchmark.yml
- README.dev.md
- benchmark/benchmarks.jl
Use a new benchmarking package, AirspeedVelocity.jl.
Benchmark on Pull Requests now IF there is a label `benchmark`.
There will be a benchmark comment, much nicer than before.
Benchmarks will use the EU data set.
Benchmarking will be slow, but it will show the comparison results in the screen.
Closes #235 
> Update benchmark action

- .gitignore
- Project.toml
- src/TulipaEnergyModel.jl
- src/run-scenario.jl
- test/test-case-studies.jl
> Add log file

- src/io.jl
- test/test-io.jl
> Added strict flag to check all assets have partition data

- benchmark/benchmarks.jl
This will allow comparing alternatives to #294 using the benchmark script.
Closes nothing
> Comment out direct_usage from benchmarks.jl to allow comparison in the EU case

- .github/workflows/Benchmark.yml
- README.dev.md
Only run the Benchmark.yml workflow if the PR and the target branches are in the same repo.
Add information to the documentation about running the benchmark by pushing to the main repo.
Closes #403
Closes #234 
> Only run Benchmark if not in a fork and document

- CONTRIBUTING.md
- README.dev.md
> Split CONTRIBUTING out of README.dev

- README.dev.md
Rearrange the locations of some commands
Closes #417 
> Minor edits in dev.md

- benchmark/benchmarks.jl
- benchmark/profiling.jl
- docs/src/tutorial.md
- src/create-model.jl
- src/solve-model.jl
- src/structures.jl
- test/test-case-studies.jl
Uses DataFrames to linearize the indices of the variables, expressions and constraints.
The tutorial has been slightly increased and changed to incorporate the new changes.
Closes #294 
> Use DataFrames to linearize indices

- test/test-case-studies.jl
Remove Cbc from the tests to prevent error on Mac M1
Closes #447 
> Don't test using Cbc to prevent error on Mac M1

- src/structures.jl
Export `EnergyProblem` in TulipaEnergyModel package
Closes #463 
> Export EnergyProblem in structures.jl

- Project.toml
> Release 0.6.1

- docs/src/how-to-use.md
- src/structures.jl
Edit docstring and documentation with (mostly) the same content.
I intended to use `@docs` for avoid duplication, but it did not work (perfectly) yet. I turned it into a discussion #484.
Closes #471 
> Improve docs for `EnergyProblem`

- docs/Project.toml
- docs/src/tutorial.md
Replace Cbc by GLPK in the tutorial.
Closes #490
> Replace Cbc by GLPK in the tutorial

- src/solve-model.jl
- src/structures.jl
Implement Solution structure and add to EnergyProblem.
It is possible to move some of login in the output of the model to the solution constructor, although I am not sure it that is actually beneficial, and it will look out of place.
Closes #492 
> Implement Solution structure and add to EnergyProblem

- .github/workflows/Test.yml
Remove nightly from tests.
Closes NA
> Remove nightly from tests

- .github/workflows/Test.yml
- .github/workflows/TestOnPR.yml
> Update codecov action to v4

- .github/workflows/Benchmark.yml
Add memory table to the benchmark report.
Closes #502
> Add memory table to the benchmark report

- src/structures.jl
- test/test-case-studies.jl
- test/test-io.jl
Add more outputs to the display of `EnergyProblem`
Closes #510 
> Add optimization problem size info to the display of `EnergyProblem`

- src/create-model.jl
The suffix is not necessary, since the name of the dataframe is enough to inform the resolution
Closes #468
> Rename flow columns in the constraints dataframes to ignore the suffix _lowest and _highest

- docs/src/how-to-use.md
- src/create-model.jl
- src/solve-model.jl
- src/time-resolution.jl
Use a more descriptive "index" for time_block traversal. We used `B` before, but after changing to data frames that was improved, but there were some remaining cases.
Closes #470 
> Replace many instance of B by time_block

- src/create-model.jl
Incoming and outgoing flows share the same loop now.
Closes #529 
> Refactor add_expression_terms_intra_rp_constraints

- .JuliaFormatter.toml
- README.dev.md
- src/TulipaEnergyModel.jl
- src/create-model.jl
- src/io.jl
- src/solve-model.jl
- src/structures.jl
- src/time-resolution.jl
using Package should not be used anymore. Instead, explicitly use
using Package: A, B, C to load objects A, B, and C. Also, don't
do that for all objects, only obvious candidates. More information
is included in the README.dev.md new section on code format guidelines.
Closes #431
> Don't use unqualified using and update README.dev.md with guidelines

- docs/src/tutorial.md
- src/create-model.jl
- src/input-tables.jl
- src/io.jl
- src/structures.jl
- src/time-resolution.jl
- test/inputs/Norse/assets-base-periods-profiles.csv
- test/test-case-studies.jl
Most notable cases are the names and types of assets and profiles. Some loose keys were also included in this. Note that partition definitions are still Strings, since they will be manipulated as Strings.
The only file change was the name of the max and min profiles, since they had dashes in their name. To avoid changing the file name, I sanitize it to convert - to _.
Closes #540 
> Use Symbols instead of Strings for many cases

- README.dev.md
For some reason, some of the indentation in PR #552 went wrong. This PR fixed it.
Closes #539 
> Fix README.dev

- docs/src/how-to-use.md
- src/solve-model.jl
Update documentation for new energy_problem and solution structure.
Closes #506 
- [NA] Lint is passing
> Update energy_problem.solution documentation

- src/io.jl
Add functions to interpolate storage levels
Closes #553 
> Interpolate storage levels

- docs/src/how-to-use.md
Add a section to the docs to point users toward JuMP's infeasible solution functions.
Unfortunately these don't work for all solvers (for instance HiGHS) - so we should maybe add more info on how to work with HiGHS and other solvers later.
Closes #472
-   [NA] Tests are passing
-   [X] Lint is passing
> Add infeasible section to docs

- docs/src/features.md
- docs/src/tutorials.md
Update documentation for Milestone 1 release
NA
> Update documentation for M1 release

- test/test-case-studies.jl
Add the storage example to the tests of the model
Closes #569 
> Add test for Storage assets case study

- docs/src/features.md
- docs/src/formulation.md
Update mathematical formulation according to the latest comments.
Closes #467 
> Update mathematical fomulation

- Project.toml
-   [X] Tests are passing
-   [X] Lint is passing
> Release 0.8.0

- .gitignore
- README.dev.md
- docs/src/formulation.md
Update the documentation according to comments from @gzclarence 
Closes #586 
> Update formulation in the documentation

- test/test-case-studies.jl
Using `JuMP.is_solved_and_feasible` makes us focus on the feasibility and optimality of the Norse case rather than the objective value.
Closes #593 
> Update Norse case test to use JuMP.is_solved_and_feasible

- README.dev.md
Fix a typo in the python environment setup for `pre-commit`
-   [x] ~Tests are passing~
> Fix command typo in README.dev.md

- src/io.jl
- src/solve-model.jl
- src/structures.jl
- test/inputs/Norse/assets-data.csv
- test/inputs/Norse/flows-data.csv
Include the new variable result $v^{\text{inv energy}}_{a}$ to the solution structure and create a new .csv file to export with the results.
Closes #626 
> Output energy storage investment to the solution

- docs/src/formulation.md
- docs/src/how-to-use.md
Update documentation to include the constraints when the energy storage can't charge and discharge simultaneously. In addition, update on the how-to section to set up the parameters in the model for this feature.
Closes #640 
> Update documentation with formulation to avoid storage charging and discharging simultaneously 

- src/constraints/capacity.jl
- src/create-model.jl
- src/time-resolution.jl
- test/inputs/Norse/assets-data.csv
- test/inputs/Norse/flows-data.csv
- test/inputs/Norse/flows-rep-periods-partitions.csv
- test/test-case-studies.jl
Create the new variables and constraints according to #640 in the model to avoid charging and discharging simultaneously for energy storage assets.
Closes #639 
> Create new variable and constraints for the `use_binary_storage_method`

- src/TulipaEnergyModel.jl
- src/create-model.jl
- src/run-scenario.jl
- src/solve-model.jl
Add more timers to the log 
Closes #584
> Add more timers to the log

- docs/src/formulation.md
Maximum and minimum intertemporal-limits equations for producers assets.
Closes #652 
> Update documentación of limits constraints for producer assets

- src/create-model.jl
- src/io.jl
- src/run-scenario.jl
- src/solve-model.jl
Reallocate timing out of the scenario function
Closes #667 
> Move timing from run scenario

- src/create-model.jl
Refactor the code to improve the readability and creation of the dataframes for the inter-rp constraints.
Closes #659 
> Refactor code to use a function to create the inter-rp dataframes

- docs/src/how-to-use.md
- src/io.jl
- test/inputs/Tiny/assets-timeframe-partitions.csv
- test/inputs/Tiny/assets-timeframe-profiles.csv
- test/inputs/Tiny/flows-timeframe-partitions.csv
- test/inputs/Tiny/flows-timeframe-profiles.csv
These tables are already  permitted to be empty. Not they
are permitted to not exist at all.
Closes #674
> Allow timeframe and partitions tables to be missing

- Project.toml
Release will be necessary to have a standalone pipeline.
We might need another release for official M2 closure, though, so I don't know what you might find best.
> Release v0.9.0

- docs/src/how-to-use.md
- src/input-schemas.jl
- src/io.jl
- test/inputs/Tiny/assets-rep-periods-partitions.csv
- test/inputs/Tiny/flows-rep-periods-partitions.csv
- test/inputs/Tiny/profiles-timeframe.csv
I noticed that I missed file `profiles-timeframe.csv` and then I noticed a few extra things that I missed.
Related to #674 
> Fix allowing timeframe and partitions tables to be missing (#674)

- README.dev.md
active -> activate
-   [X] Tests are passing
-   [X] Lint is passing
> FIX README.dev.md

- Project.toml
> Release v0.9.2

- docs/src/api.md
- docs/src/formulation.md
- docs/src/how-to-use.md
- docs/src/index.md
- docs/src/reference.md
- docs/src/tutorials.md
Closes #592
-   [X] Tests are passing
> Make docs friendlier and FIX broken links

- docs/src/tutorials.md
- src/constraints/capacity.jl
- src/constraints/consumer.jl
- src/constraints/energy.jl
- src/constraints/storage.jl
- src/constraints/transport.jl
- src/create-model.jl
- src/input-schemas.jl
- src/io.jl
- src/structures.jl
- src/time-resolution.jl
- test/test-case-studies.jl
- test/test-io.jl
To use DuckDB types
Closes #705 
> Change Symbols to Strings for input data

- benchmark/Project.toml
- benchmark/profiling/README.md
- benchmark/profiling/basic.jl
- benchmark/profiling/common.jl
- benchmark/profiling/eu-pre-model.jl
Creates more details on profiling. All information is in a separate folder for now, but it can be moved to the developer documentation and merged with the current information.
No related issues
> Create profiling folder with instructions

- benchmark/profiling/common.jl
Small fix that we did yesterday.
> Add missing BenchmarkTools in the profiling script

- docs/src/how-to-use.md
QUICK FIX
-   [NA] Tests are passing
> Edit concepts and how-to-use

- CITATION.cff
Update CFF file to have the authors in alphabetic order
Closes #619 
> Update CFF file

- utils/csv-modifications.jl
Creates a new folder `utils` to keep files that are useful for devs only, might be
deleted at any moment, might change, are not tested, etc., but that are useful
for small things.
Creates a file `utils/csv-modifications.jl` to help make modifications to
Tulipa's CSV files. This includes changing the unit line.
NA
> Create utils/csv-modifications.jl to help making changes in CSVs

- docs/src/formulation.md
- docs/src/how-to-use.md
Update formulation and how-to sections
Closes #743 
> Update documentation with groups information

- src/create-model.jl
The changes ensure that the dataframe "units_on_and_outflows" is calculated in the highest resolution of the asset and the flow.
Closes #763 
> Update UC and ramping dataframe

- docs/src/tutorials.md
- src/constraints/capacity.jl
- src/constraints/consumer.jl
- src/constraints/conversion.jl
- src/constraints/energy.jl
- src/constraints/group.jl
- src/constraints/hub.jl
- src/constraints/investment.jl
- src/constraints/ramping-and-unit-commitment.jl
- src/constraints/storage.jl
- src/constraints/transport.jl
- src/create-model.jl
- src/input-schemas.jl
- src/io.jl
- src/solve-model.jl
- src/structures.jl
- src/time-resolution.jl
- test/test-case-studies.jl
- test/test-io.jl
**Work in progress**
Simplify and try to refactor the code in #741 to make a more manageable pull request.
Implement basic multi-year support.
Related to #740 and #741
> Add basic multi-year support

- src/constraints/ramping-and-unit-commitment.jl
- src/create-model.jl
Fix the conditions on the constraints creation and binary definition of the unit commitment variables.
> Fix unit commitment conditions in the constraints

- docs/src/formulation.md
- docs/src/how-to-use.md
Add formulation and how-to use the unit commitment and ramping constraints in the model
Closes #750 
> Update docs with UC and Ramps

- docs/src/formulation.md
- docs/src/how-to-use.md
- src/constraints/group.jl
- src/create-model.jl
The constraints do not change with the multi-year investment since they are meant to limit the investments that you can make each year rather than limiting the accumulated investments.
The changes here clarify this in the documentation and improve the code's performance.
Closes #789 
> Refactor group constraints to improve performance

- src/create-model.jl
- src/io.jl
- Add a function to calculate the intervals of the milestone years
- Add weights to operation costs terms
Closes #816 
> Add operation weights

- src/constraints/capacity.jl
- src/constraints/storage.jl
- src/create-model.jl
- test/inputs/Multi-year Investments/graph-assets-data.csv
- test/inputs/Multi-year Investments/initial-assets-data.csv
Update the energy storage limit to consider the accumulated energy investment in the multi-year development. The storage assets will only use the simple method.
Part of #806 
> Update energy storage constraints with multi-year investment

- src/constraints/capacity.jl
- src/create-model.jl
Update storage binary constraints with multi-year investment
Part of #806
> Update storage binary constraints with multi-year investment

- src/TulipaEnergyModel.jl
- src/create-model.jl
- src/economic-parameters.jl
- test/test-economic-parameters.jl
New file, functions, and tests for the economic parameter calculations
Closes #826
> Add new economic parameters functions

- src/create-model.jl
- src/economic-parameters.jl
> Put weights in the objective function

- src/constraints/capacity.jl
- src/create-model.jl
Add accumulated investment limit to the storage binary constraints
Closes #806 
> Add accumulated investment limit to binary storage constraints

- test/test-case-studies.jl
> Add objective value to multi-year test

- Project.toml
> Release 0.10.0

- README.md
- docs/make.jl
- docs/src/10-how-to-use.md
- docs/src/20-tutorials.md
- docs/src/30-concepts.md
- docs/src/40-formulation.md
- docs/src/90-contributing.md
- docs/src/91-developer.md
- docs/src/index.md
Change order of sections & nesting
Fix contents sections of pages
Closes #855
> Fix links to contributing & developer

- .all-contributorsrc
- .copier-answers.yml
- CITATION.cff
- Project.toml
- docs/make.jl
Update the authors list.
Move some people to the new all contributors (will be done in the comments in the PR)
> Update the authors list in various files

- docs/src/10-how-to-use.md
Closes #847
- [NA] Lint workflow is passing
> Fix italics in schema list

- README.md
> Fix links to contributing and developer documentation

- docs/src/40-formulation.md
> Modify docs flow lower bound

- docs/src/20-tutorials.md
- src/TulipaEnergyModel.jl
- src/constraints/storage.jl
- src/create-model.jl
- src/io.jl
- src/model-preparation.jl
- src/solve-model.jl
- src/structures.jl
- src/time-resolution.jl
- src/utils.jl
- src/variables/flows.jl
- src/variables/investments.jl
- src/variables/storage.jl
- src/variables/unit-commitment.jl
- test/test-pipeline.jl
> Create TulipaVariable struct and define variable tables

- .github/workflows/Lint.yml
- .lychee.toml
- codecov.yml
- **Add debug step to Lint workflow**
- **Add JuliaFormatter at version 1 in the Lint workflow**
- **Fix link exclusion in lychee**
- **Add codecov patch target (95%)**
> Various small fixes

- src/constraints/capacity.jl
- src/constraints/consumer.jl
- src/constraints/conversion.jl
- src/constraints/group.jl
- src/constraints/hub.jl
- src/constraints/investment.jl
- src/constraints/ramping-and-unit-commitment.jl
- src/constraints/storage.jl
- src/constraints/transport.jl
- src/create-model.jl
- **add_*_constraints!: unpack sets inside contraint builder functions**
- **add_transport_constraints!: remove unused function argument**
Closes #892
> Unpack sets inside `add_*_constraints!` functions

- docs/src/10-how-to-use.md
> Add how-to for multi-year investments

- src/constraints/capacity.jl
- src/constraints/transport.jl
- src/create-model.jl
- src/structures.jl
- src/variables/flows.jl
> Create flow variables using the indices table

- src/create-model.jl
- src/variables/unit-commitment.jl
> Create units_on variables using the indices table

- docs/src/40-formulation.md
The description was put wrong.
> [docs] Modify the description of the parameter discounting factor operation cost 

- docs/src/20-tutorials.md
- src/TulipaEnergyModel.jl
- src/io.jl
- src/model-preparation.jl
- src/structures.jl
- src/time-resolution.jl
- src/tmp.jl
- test/test-pipeline.jl
- utils/scripts/split-graph-data.jl
The partition table is being created in a tmp.jl file to help
in the refactor.
Related to #895
> Start transition from DataFrames to DuckDB

- docs/src/91-developer.md
> Add new package section to dev docs

- src/model-preparation.jl
> Move units_on from DF to DuckDB

- src/model-preparation.jl
- src/time-resolution.jl
- src/tmp.jl
> Add `highest_in` to `create_constraints_indices`

- src/model-preparation.jl
> Fix: remove duplicate tmp_create_constraints_indices

- test/inputs/Tiny/bad-assets-data.csv
- test/test-io.jl
> Remove bad asset test

- docs/src/10-how-to-use.md
- docs/src/20-tutorials.md
- src/run-scenario.jl
> Add docs for enables_names = false

- src/constraints/create.jl
- src/constraints/transport.jl
- src/create-model.jl
> Create transport table and update transport.jl

- src/constraints/conversion.jl
- src/constraints/energy.jl
- src/constraints/hub.jl
- **[hub] Update hub.jl to use attach_constraint**
- **[conversion] Update conversion.jl to use attach_constraint**
- **[energy] Update energy.jl to use attach_constraint**
Part of #642 and since there is no graph in hub and conversion, part of #942 as well.
> Update constraint files hub.jl, conversion.jl and energy.jl to use attach_constraints

- docs/src/10-how-to-use.md
- docs/src/20-tutorials.md
- src/constraints/create.jl
- src/constraints/storage.jl
- src/io.jl
- src/model-preparation.jl
- src/solve-model.jl
- src/structures.jl
- src/variables/create.jl
- src/variables/storage.jl
- **Replace all intra_rp by rep_period and inter_rp by over_clustered_year**
Closes #642
> Replace all intra_rp by rep_period and inter_rp by over_clustered_year

- .github/workflows/Test.yml
- .github/workflows/TestOnPRs.yml
- Project.toml
- src/create-model.jl
- Fix to speed up the creation of the model when using representative periods and inter-temporal constraints
- New release v0.10.3
> Fix to improve inter-rp expression creation time

- docs/src/60-structures.md
- src/TulipaEnergyModel.jl
- src/constraints/create.jl
- src/data-preparation.jl
- src/io.jl
- src/structures.jl
- src/variables/create.jl
- test/runtests.jl
- test/test-pipeline.jl
This includes the creation of the unrolled partition tables, the
merged tables (previously union tables), and the lowest and highest
resolution tables.
Related to #701
> Create src/data-preparation.jl and move creation of partition-related tables there

- src/constraints/create.jl
- src/constraints/transport.jl
- src/model-preparation.jl
- src/objective.jl
- src/variables/create.jl
- src/variables/flows.jl
Rename "from" and "to" to "from_asset" and "to_asset" uniformly.
Blocked until #1061 is merged
> Rename "from" and "to" to "from_asset" and "to_asset" uniformly.

- Project.toml
Update DuckDB version to 1.2.1
Closes #1074
> Update DuckDB version to 1.2.1

- src/run-scenario.jl
- src/structures.jl
- test/io-outputs/energy-problem-empty.txt
- test/io-outputs/energy-problem-model-created.txt
- test/io-outputs/energy-problem-model-infeasible.txt
- test/io-outputs/energy-problem-model-solved.txt
- test/test-case-studies.jl
- test/test-io.jl
- test/test-options.jl
> Clean test printing

- src/constraints/group.jl
Remove `...` and explicitly list the arguments. 
Closes #723
> Fix docstrings of add_group_constraints

- benchmark/benchmarks.jl
@datejada, similar to #1089.
Probably, if we don't benchmark from scratch, then we are skipping some table creation.
None.
> Add setup steps to benchmark to properly run from scratch

- src/data-validation.jl
- test/test-data-validation.jl
Check that only transport flows are investable 
Closes #1101
> Validate that only transport flows can be investable

- src/constraints/ramping-and-unit-commitment.jl
- src/data-preparation.jl
> Remove asset_both and asset_milestone from unnecessary places in data-preparation.jl

- .github/workflows/CompareMPS.yml
Add conditional to CompareMPS steps to prevent PR comments on forks.
Closes #1126
> [WIP] Fix CompareMPS for forks

- src/data-preparation.jl
> Add docstring to create_merged_tables!

- Project.toml
> Release 0.14.1

- docs/src/91-developer.md
Documenter.jl doesn't render in-line HTML. - it's an open issue.
Closes #1134
> Remove broken HTML syntax tags

- docs/src/20-how-to-use.md
- src/create-model.jl
- src/run-scenario.jl
- src/solve-model.jl
- test/test-case-studies.jl
- test/test-options.jl
- test/test-pipeline.jl
> Add option to use JuMP direct model

- src/data-preparation.jl
- src/data-validation.jl
- src/input-schemas.json
- src/io.jl
- src/model-preparation.jl
- test/data-simplest.jl
- test/test-data-validation.jl
- test/test-defaults.jl
- test/test-pipeline.jl
- test/utils.jl
> Create function to populate defaults

- src/solve-model.jl
> Remove save_solution from solve_model arguments

- src/data-validation.jl
- test/test-data-validation.jl
- test/utils.jl
> Add validation between `use_binary_storage_method` and `investment_limit`

- src/objective.jl
- test/test-case-studies.jl
> Modify operation discounting for multi-year investments

- docs/src/91-developer.md
> Update developer's instructions

- docs/src/30-concepts.md
- docs/src/40-formulation.md
- docs/src/45-scientific-references.md
- docs/src/55-outputs.md
This pull request updates the documentation for the Tulipa energy modeling framework, focusing on improving clarity, reorganizing references, and enhancing user guidance. The most significant changes include adding a new "Scientific References" section, updating reference links throughout the documentation, and renaming the outputs file for better organization.
* **New "Scientific References" Section**: Introduced a dedicated `scientific-references.md` file to consolidate all academic references, categorized by topic (e.g., flexible temporal resolution, storage modeling, ramping, and unit commitment). This improves accessibility and organization of references.
* **Updated Reference Links**: Replaced outdated `@ref math-references` links with `@ref scientific-refs` in multiple …
> Add new section with the scientific references

- src/model-preparation.jl
> 1037_fixpartiallydocs

- docs/src/20-how-to-use.md
- docs/src/30-concepts.md
- docs/src/40-formulation.md
- docs/src/55-outputs.md
- src/constraints/energy.jl
- src/constraints/storage.jl
- src/model-preparation.jl
- src/variables/storage.jl
> Replace inter-temporal and intra-temporal in docs

- src/model-preparation.jl
> Fix list in docstring

- Project.toml
> Release 0.15.1

- src/constraints/ramping-and-unit-commitment.jl
Improve the hotfix for the alignment of `units_on` and compact method in #1195.
These constraints are indexed already by `var_units_on` filtered by the investment methods, so it is possible to obtain the index of `units_on` directly in the original indice function.
N/A
> Improve the hotfix for the alignment of `units_on` and compact method

- src/constraints/create.jl
- src/constraints/flows-relationships.jl
- src/create-model.jl
- src/sql/create-constraints.sql
- test/test-constraint-flows-relationship.jl
- test/utils.jl
- Add sql query to create the constraints indices
- New file to create the constraints
- Add expressions to get the ids and durations of the flows participating in the relationship
- Add test for the constraint
Closes #1189 
- [N.A.] Docs were updated and workflow is passing
> Add flows relationship constraints

- src/constraints/storage.jl
- src/data-preparation.jl
- src/data-validation.jl
- src/model-preparation.jl
- src/objective.jl
- src/structures.jl
- src/utils.jl
- test/test-defaults.jl
Simple test to ensure things won't go awry.
Closes #1206
> Add test to make sure that populate_with_defaults doesn't drop extra columns

- docs/src/91-developer.md
- Delete the descriptions of Prettier, as it is no longer used.
- Add a warning that JuliaFormatter VSCode extension should not be used.
> [docs] Minor updates developer documentation

- docs/Project.toml
- docs/src/11-workflow-with-obz.md
Add a full workflow tutorial using OBZ data.
Blocked by #1215 
Closes #
> Add workflow tutorial using OBZ data

- docs/src/40-formulation.md
> Fix typo in the documentation

- docs/src/45-scientific-references.md
- Update the link for the new publication!
- Modify the rest of the references to have a consistent citation style (APA)
> Update scientific references

- docs/src/20-user-guide/55-outputs.md
- src/create-model.jl
- src/sql/create-variables.sql
- src/variables/create.jl
- src/variables/flows.jl
- test/inputs/Multi-year Investments/flow-commission.csv
- Add new variable: vintage flow
- Add its lower bound
- Fix some broken links in the docs
Closes #1247, #1279
> Add vintage flow variable

- docs/src/40-scientific-foundation/40-formulation.md
- docs/src/40-scientific-foundation/45-scientific-references.md
This PR includes:
- Changes in the formulation to include the two-stage stochastic programming optimization in the model
- Add @lottekremer master's thesis as a reference for the formulation
Closes #1282
> [docs]: Two-stage stochastic programming formulation changes

- test/test-constraint-dc-opf.jl
- test/test-constraint-flows-relationship.jl
- test/test-constraint-limit-decommission-compact-method.jl
- test/test-constraint-vintage-flow-sum.jl
- test/utils.jl
> Add new function for creating tables in constraint tests

- benchmark/EU/asset-commission.csv
- docs/src/40-scientific-foundation/40-formulation.md
- src/constraints/conversion.jl
- src/input-schemas.json
- test/inputs/MIMO/asset-commission.csv
- test/inputs/Multi-year Investments/asset-commission.csv
- test/inputs/Norse/asset-commission.csv
- test/inputs/Power-flow/asset-commission.csv
- test/inputs/Storage/asset-commission.csv
- test/inputs/Tiny/asset-commission.csv
- test/inputs/UC-ramping/asset-commission.csv
- test/inputs/Variable Resolution/asset-commission.csv
> [Multi-year Part II] Change the name of conversion efficiency
