TulipaEnergy/TulipaEnergyModel.jl

.github/workflows/Benchmark.yml, .gitignore, benchmark/Project.toml, benchmark/benchmarks.jl, src/model.jl
Creates a benchmark suite in file `benchmark/benchmarks.jl`.
Creates a workflow to run the benchmark when there is a new relevant pull request.
The workflow compares the current pull request with `origin/main`.
The comparison is posted in the pull request. An example can be seen here: https://github.com/abelsiqueira/TulipaBulb.jl/pull/2#issuecomment-1684434428
One alternative would be running only when a specific comment is written at a pull request. For instance, writing "/benchmark" starts the benchmark. This adds an extra step and, in return, we avoid running benchmarks for every new PR. Should we leave for later?
Closes #13 
=> Create benchmark and GitHub workflow to run it on PRs

.github/workflows/CompatHelper.yml
Allow CompatHelper to use DOCUMENTER_KEY.
Hopefully solves it.
Related
- #39 
=> Allow CompatHelper to use DOCUMENTER_KEY

.github/workflows/Benchmark.yml, README.dev.md
This implements a `/run-benchmark` "command" that anyone can use in PRs to trigger the `Benchmark.yml` workflow.  After the workflow completes, it responds to the PR with a comment containing the results.  The results from `BenchmarkCI` doesn't seem like to be markdown formatted, so I wrapped it in a source block.  We could also try to parse it into nice markdown if we want.  The workflow also has an (incomplete) `workflow_dispatch` trigger, which could be used to manually run it for a specific branch/tag.  To support this use, the workflow also generates a "step summary" that is shown in the GH actions workflow run page.
You can see this in action in [this repo](https://github.com/suvayu/fictional-giggle/pull/5). In the example repo there's nothing to benchmark, so it just responds with …
=> Custom command to run benchmark from a PR

.github/workflows/Benchmark.yml
The workflow_dispatch event accepts a fork and branch parameter,
and runs the benchmark workflow on it.  The results are shown in the
step summary
- #59
=> Benchmark workflow runnable as workflow_dispatch

.github/workflows/TestOnPR.yml
TestOnPr.yml is a copy of Test.yml that runs only version 1 and os ubuntu-latest.
The coverage is also only reported on version 1 of ubuntu-latest since the PRs only run that.
Closes #133 
=> Create TestOnPR workflow with a lighter test load

README.dev.md, benchmark/benchmarks.jl
The benchmarks now run on the `tiny` data.
The benchmarks now run the `create_graph` function as well.
The old functions have been updated to use the `graph`.
Closes #146 
=> Fix benchmarks and add info on how to run it manually

src/model.jl, test/runtests.jl
1. Include an infeasible model in the test 
2. Add a check in the model after the solve to determine the status
Closes #149
=> Add infeasible run test

src/TulipaEnergyModel.jl, src/time-resolution.jl, test/runtests.jl
One assumption is made: the description of a time period is a range, i.e., an object `start:end`.
Creates a function `compute_rp_periods` that receives a list of time steps (such as the time steps of various flows), and computes the periods for that representative period.
Creates a function `resolution_matrix` that computes the matrix of a given flow/asset in a given representative period.
Closes #109 
=> Add functions to compute time resolution periods and matrices

src/io.jl
Since all our files use `header = 2`, it makes sense to have it as default.
Closes #167 
=> Refactor header argument into read_csv_with_schema

benchmark/benchmarks.jl, test/Project.toml, test/runtests.jl
Fix the benchmarks.jl file with the new changes.
Use Norse data for the benchmarks.
Add a test `include`ing the benchmarks to make sure that the syntax is correct. This should avoid having to fix the benchmarks.jl.
Closes #170 
=> Use Norse data on the benchmarks

test/test-case-studies.jl
The infeasible test used to produce a warning - now that warning is caught so the test passes without warning
Avoids having a "consistent warning"
Closes #190
=> Add warning catch for infeasible test

Project.toml, src/time-resolution.jl, test/test-time-resolution.jl
Adds the arguments `rp_time_scale` to the time resolution matrix function.
This value is multiplied by the matrix.
The tests were updated to try different values for the time scale.
Also, since there is floating-point arithmetic going on now, the comparison has to be approximate, not equal anymore.
Closes #178 
=> Multiply the time-resolution matrices by the rp time scale/duration

docs/src/mathematical-formulation.md
Fixed bad rendering of Sets area (hopefully) as well as broke formulas into two lines by adding a break before the "includes all" part of each.
Closes #202
=> Updated documentation to fix linebreaks

src/time-resolution.jl, test/test-time-resolution.jl
Add a `strategy` keyword that allows changing how the `rp_periods` are computed. The default strategy is the greedy strategy that was already implemented. The new strategy is `:all`, which uses all breakpoints.
Closes #188 
=> Implement :all strategy for computing rp_periods

src/io.jl, src/model.jl, src/time-resolution.jl, test/inputs/Norse/flows-time-intervals.csv, test/test-case-studies.jl
=> Model the different time resolutions

README.dev.md
- Set Unix command to activate a Python virtual environment as default with Windows instructions as clarification
- replace generic 'pkg' with 'TulipaEnergyModel' or 'docs' to match what should actually be shown in the terminal
=> Update README.dev.md for consistency

benchmark/benchmarks.jl
Instead of writing to the test folder, write to some random place, since the output is ignored. This random place will be deleted after the Julia call is done, so it won't overflow the disk.
I haven't written to /dev/null because that would require changes to the write output function itself or some ugly workaround. Since the code is not a bottleneck, this should suffice.
Closes #230 
Closes #193 
=> Use a random tmp dir to write the solver output in the benchmark

src/model.jl
Removes e_ and c_.
Closes #229 
=> Remove single-letter prefix for expressions and constraints

src/input-tables.jl, src/io.jl, src/model.jl, src/time-resolution.jl, test/inputs/Norse/assets-partitions.csv, test/inputs/Norse/flows-partitions.csv, test/inputs/Norse/flows-time-intervals.csv, test/inputs/Norse/rep-periods-data.csv, test/inputs/Tiny/assets-partitions.csv, test/inputs/Tiny/assets-time-intervals.csv, test/inputs/Tiny/flows-partitions.csv, test/inputs/Tiny/flows-time-intervals.csv, test/inputs/Tiny/rep-periods-data.csv, test/test-io.jl, test/test-time-resolution.jl
Rename symbols according to #208
Closes #208
=> Rename time symbols

src/model.jl
Change constraint to lower bound for the flows
Closes #224 
=> Change constraint to bound

src/model.jl, test/test-case-studies.jl
Creates a function for the sum of the flow profile over the time block.
Also changes the assets_profiles_sum to be a function instead of an expression, because it does not have any variables or expression, and therefore it can be immediately computed.
Closes #264 
=> Fix summation of flow profile over time block

benchmark/benchmarks.jl, src/io.jl, src/model.jl, src/run-scenario.jl, src/structures.jl, test/test-case-studies.jl, test/test-io.jl, test/test-model.jl
Edit: The old text is below the separator.
This PR stores the solution to the problem inside the graph structure.
It also saves the objective value inside the energy problem structure.
---
@datejada, this PR became too long, but splitting will take some time, and explaining in the parts will be hard. So I will explain it here, while I think of how to split this, ok?
This PR makes the structure EnergyProblem hold many things necessary to make it the center of attention. It still keeps the EnergyModel creation and solving separated with different functions. The benefits are not clear, since it depends if anyone will want to use these at all without the EnergyModel. Let me know if it is better to remove it.
Originally, it was meant to be #268, which involves changing the assets and flows …
=> Store the solution inside the graph structure and the objective value inside the problem struct

src/io.jl, src/model.jl, src/run-scenario.jl, test/test-model.jl
Allow creating the graph and representative_periods without creating an EnergyProblem.
Return a solution from `solve_model!` so the solution object is not lost.
These changes mean that the user can follow the pipeline with or without the EnergyProblem.
Closes #293 
=> Allow user to decide whether to use EnergyModel or not

src/time-resolution.jl, test/test-time-resolution.jl
- Remove function `resolution_matrix`
- Remove its tests
Closes #351 
=> Remove obsolete function `resolution_matrix`

docs/Project.toml, src/solve-model.jl, test/runtests.jl, test/test-options.jl
This still allows specifying the default parameters using a function, while allowing defining default parameters of solvers that were not loaded.
Now all of these work:
- `default_parameters(Val(:HiGHS))`
- `default_parameters(HiGHS.Optimizer)`
- `default_parameters(:HiGHS)`
- `default_parameters("HiGHS")`
But only the first is dispatching on the type.
Closes #376 
=> default_parameters now dispatches on Val types

test/runtests.jl
We now include all files starting with `test-` and ending with `.jl`
Closes #409 
=> Add an extra condition to only include files ending with .jl

src/create-model.jl, src/structures.jl, test/test-case-studies.jl
Change the display of EnergyProblem variable, now it shows 
- termination_status
- solved
- objective_value
Closes #321 
=> Change display of EnergyProblem variable

.github/workflows/Test.yml, .github/workflows/TestOnPR.yml, src/TulipaEnergyModel.jl
Tentative solution to show the badge on codecov.
The src/TulipaEnergyModel.jl change is insignificant just to trigger the TestOnPR.yml workflow.
Maybe fix #422, have to check after merging.
=> Fix running codecov only on ubuntu-latest for Julia 1

src/solve-model.jl
Add a new function to compute duals when using `energy_problem`. Cbc can't compute the duals, therefore we had to wrap the function into a try/catch block.
Closes #328 
=> Add function to compute duals

src/create-model.jl, src/solve-model.jl
Didn't build the docs locally, so hope it worked.
Closes #434
=> Added inline backticks to avoid italics from underscores

src/create-model.jl, src/run-scenario.jl
`add_efficiency` is used to create three sets for flows: _lowest resolution without efficiencies_, _lowest resolution with efficiencies_, and _highest resolution without efficiencies_.
- Remove `add_efficiency`, so flows are always attached with efficiencies. At some cases, the efficiencies are set to 1. @datejada Would you double-check the conditions (by the variable `flag`) I added?
To still be able to have the set _highest resolution without efficiencies_
- Add `use_highest_resolution`. We can open another issue if we want to get rid of this flag as well.
Also a minor edit
- Add an empty line after log display
Closes #436 
=> Always attach efficiencies to flows

src/run-scenario.jl, src/structures.jl
Add timer for `EnergyProblem`
- Time for creating the model
- Time for solving the model
Closes #474 
=> Display timer for energy problem

docs/src/how-to-use.md, docs/src/tutorial.md, src/io.jl, src/solve-model.jl, src/structures.jl
Add the new variable `storage_level_intra_rp` to the solution and outputs of the model.
Closes #509 
=> Add storage level between (intra) representative periods to the outputs

.github/workflows/Benchmark.yml, benchmark/benchmarks.jl
Use `samples = 3 evals =1 seconds = Inf` in the benchmarks, and don't tune.
Closes #534 
=> Make the number of samples explicit in the benchmark

src/io.jl, test/test-io.jl
Use the is_seasonal value of the assets to decide for which assets to compute base periods partitions.
This allows setting a default partition for assets that are seasonal but that don't have a definition at the base periods partitions file.
Closes #538 
=> Use is_seasonal to define base partitions instead of only the file

src/io.jl
We now export the storage level repeated as it is within the block instead of dividing by the duration.
Closes #548 
=> Fix repeated value calculation in save_solution_to_file function for storage level

.github/workflows/Benchmark.yml, benchmark/benchmarks.jl
Inf is not allowed in the JSON file used internally by AirspeedVelocity.jl. The BenchmarkTools package seems to handle it properly when saving, but AirspeedVelocity bypass that and uses JSON directly.
We explicitly use Inf in the benchmarks.jl script, to the simplest tentative solution is to change that to another value.
This PR changes Inf to 86400, which should be enough for any reasonable benchmark that we do.
This PR also changes the bench-on parameter to $HEAD to indicate that we run the script given in the PR (otherwise we can't test this change before merging).
Closes #588  …
=> Change Inf to 86400 in the benchmarks.jl script and benchmark on the HEAD script

docs/src/how-to-use.md, docs/src/tutorials.md, src/io.jl, src/structures.jl, test/runtests.jl, test/test-io.jl
The function to create graph et al from a csv folder has been split into two functions. The first reads the csv folder into a new TableTree structure. The second processes the TableTree structure into graph et al.
Closes #544 
=> Refactor io into reading and processing and create table tree structure

src/constraints/consumer.jl, src/constraints/conversion.jl, src/constraints/hub.jl, src/constraints/transport.jl, src/create-model.jl, src/io.jl
This improves the filter function based on investigations on performance and online comments.
A summary seems to be:
- Use `filter` in the DataFrames syntax (`filter(:column => action, df)`) instead of `subset` (might not be true always).
- When possible, use the "implicit" functions  (don't know actual name), i.e., instead of `:column => x -> x == value`, use `:column => ==(value)`. The `==(value)` generates a function that checks for equality to `value`.
- Use `view=true`, when possible. This we knew.
=> Update filter usage to be more efficient

README.dev.md
The Code format & guidelines section appeared twice in the document (probably a mistake from rearranging the structure of the sections a while back) so I removed the extra.
No issue - quick fix
-   [X] Tests are passing
-   [X] Lint is passing
=> Remove duplicate "Code format & guidelines" section

src/create-model.jl, src/io.jl, src/solve-model.jl, src/structures.jl
To avoid changing the EnergyProblem structure too much because of timing, we create a timings dictionary.
We time the constructor of EnergyProblem instead of the function that reads the CSV folder. This way we time the functions inside the constructor, which are the expensive functions in the input.
This also allows EnergyProblem constructed directly to have times.
Closes #680
=> Create timing dict for EnergyProblem and time constructor

docs/src/concepts.md, src/constraints/energy.jl, test/inputs/Norse/assets-data.csv
The aggregation function in the function `add_energy_constraints!` must be `sum`, not `Statistics.mean` 
Closes #692 
=> Refactor energy constraints to use sum instead of mean

src/run-scenario.jl
Added a version of run_scenario function that uses a connection rather than input folder.
Still needs proper testing, although it appeared to work using the pipeline workflow. (Not sure how to test it.)
Do we want to remove run_scenario that uses input and output folders?
Closes #665
=> Add run_scenario(connection)

docs/src/how-to-use.md, docs/src/tutorials.md, src/io.jl, src/structures.jl, test/test-io.jl
Atomic commit to refactor the RepresentativePeriod structure to be created using DuckDB instead of table_tree
Closes #707 
Closes #495 
=> Use DuckDB to create the RepresentativePeriod structure

src/io.jl
To use DuckDB instead of tablee
Closes #710 
=> Refactor timeframes, assets, and flows to use DuckDB for input data

benchmark/Project.toml, benchmark/benchmarks.jl, benchmark/profiling/common.jl, docs/src/concepts.md, docs/src/how-to-use.md, docs/src/tutorials.md, src/input-schemas.jl, src/io.jl, test/runtests.jl, test/test-aux.jl, test/test-case-studies.jl, test/test-io.jl, test/test-model.jl, test/test-options.jl
Change schema_per_file to schema_per_table.
Change the types of the schema to a SQL/DuckDB compliant name.
This also prepares the ground to remove table_tree (#729).
Closes #734
=> Update schema to be used by TulipaIO and change name to schema_per_table

docs/src/formulation.md, src/constraints/ramping-and-unit-commitment.jl, src/create-model.jl, src/input-schemas.jl, test/inputs/UC-ramping/assets-data.csv, test/inputs/UC-ramping/flows-rep-periods-partitions.csv, test/test-case-studies.jl
Include the duration in the ramping constraints in the RHS of the equations to account for that the ramp parameters are given as rates.
Closes #772 
=> Include duration in the ramping constraints

src/create-model.jl, src/io.jl, src/structures.jl
Add the investment method to the graph structure to differentiate the investment method to use it in the model. Currently, the parameter is read, but it is not available in the graph.
Closes #787 
=> Add investment method to the graph structure

src/constraints/capacity.jl, src/constraints/ramping-and-unit-commitment.jl, src/create-model.jl
Generalization of the accumulated units for all assets (including the ones that are not investable). This generalization simplifies the code in the capacity, unit commitment, and ramping constraints.
Closes #790 
=> Update UC and ramping constraints with accumulated units

Project.toml
DuckDB.jl 1.1 on Windows is broken with an error
'Could not load symbol duckdb_vector_size'
This limits the DuckDB version until that is fixed.
refs:
- duckdb/duckdb#13911
=> Limit DuckDB version to 1.0 until duckdb/duckdb#13911 is fixed

src/TulipaEnergyModel.jl, src/create-model.jl
=> Specify the domain of decommission variables

src/tmp.jl
For FI_Hydro_Reservoir in the EU case, there are no matches in the incoming
flows, so there is nothing constraining the time block. In this case, it uses
1 as time_block_start and num_timesteps and tmie_block_end of the single
block.
=> Fix case where the there are no time blocks to determine in a constraint

docs/src/91-developer.md
Text was in line with image - added carriage returns
Problem:
Closes #
=> Fix 91-developer.md

docs/src/20-tutorials.md, src/constraints/group.jl, src/constraints/investment.jl, src/create-model.jl, src/expressions/multi-year.jl, src/expressions/storage.jl, src/objective.jl, src/solve-model.jl, src/structures.jl, src/time-resolution.jl, src/variables/create.jl, src/variables/investments.jl, test/inputs/Multi-year Investments/asset-both.csv, test/test-case-studies.jl, test/test-pipeline.jl
Create field lookup to allow changing the variables without
having to redefine the whole model creation
Related to #923
=> Refactor variables to use TulipaVariable

src/constraints/ramping-and-unit-commitment.jl, src/constraints/storage.jl, src/constraints/transport.jl, src/create-model.jl, src/io.jl, src/model-preparation.jl, src/objective.jl, src/solve-model.jl, src/structures.jl, src/time-resolution.jl, src/tmp.jl, src/variables/create.jl, src/variables/flows.jl, src/variables/storage.jl, src/variables/unit-commitment.jl, test/test-pipeline.jl
**Blocked by #925**
Create all variables with connection instead of dataframes variable.
With the `lookup` created in #925, this allow us to
Close #923
=> Create all variables directly from connection and independent of dataframes

src/create-model.jl
This option is very useful if model building becomes a bottleneck.
I tested with the case: https://github.com/jump-dev/open-energy-modeling-benchmarks/tree/main/TulipaEnergyModel/cases/1_EU_investment_simple
And considered a 744-hour window.
After running:
```julia
@time for i in 1:5
@time TEM.create_model!(energy_problem, enable_names = true)
end
@time for i in 1:5
@time TEM.create_model!(energy_problem, enable_names = false)
end
```
```
6.068038 seconds (51.89 M allocations: 2.070 GiB, 14.97% gc time)
6.543459 seconds (51.89 M allocations: 2.070 GiB, 15.97% gc time)
6.146185 seconds (51.89 M allocations: 2.070 GiB, 31.12% gc time)
4.789449 seconds (51.89 M allocations: 2.070 GiB, 21.78% gc time)
5.377641 seconds (51.89 M allocations: 2.070 GiB, 28.66% gc time)
28.927705 seconds (259.45 …
```
=> Option to disable name creation

src/constraints/create.jl, src/create-model.jl, src/structures.jl, src/variables/create.jl, test/test-pipeline.jl
With the table_name, we use a different constructor, based only on
the connection and table name.
=> Store a table name inside TulipaVariable and TulipaConstraint

src/create-model.jl, src/expressions/multi-year.jl, src/expressions/storage.jl, src/io.jl, src/model-preparation.jl, src/objective.jl, src/solve-model.jl, src/structures.jl
Closes #934 
- Remove EnergyProblem.timings
- Use `@timeit` on function calls
=> Use `@timeit` on function calls

src/constraints/capacity.jl, src/constraints/ramping-and-unit-commitment.jl, src/constraints/storage.jl, src/model-preparation.jl, src/structures.jl
With the idea of allowing multiple constraints per indices table, this links the indices to the constraints. It also creates a function `attach_constraint!` to help keep things in check.
It fails the [avoid fields with abstract types](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type) recommendation (`ConstraintRef` has three parametric types), so it might be unnecessarily slow.
I see two solutions:
1. Don't store the container at all, just the names. This is probably sufficient and cleaner.
2. Store the multiple types that ConstraintRef can have, either with multiple fields, dict of dicts, or more complicated structures. I don't like this idea because it makes the code more complex and involves more JuMP specific things. However, if the container …
=> Update TulipaConstraint to allow attaching more constraints to the same indices table

src/constraints/capacity.jl, src/constraints/consumer.jl, src/constraints/conversion.jl, src/constraints/create.jl, src/constraints/energy.jl, src/constraints/hub.jl, src/constraints/ramping-and-unit-commitment.jl, src/constraints/storage.jl, src/create-model.jl, src/io.jl, src/model-preparation.jl, src/solve-model.jl, src/structures.jl, src/tmp.jl
Rename some of the constraints from Miro. Many other issues were created in #642 to handle the various edge cases and new tables, but this includes the main changes and, after merged, should allow other issues to be worked on, such as #960. 
- **Rename lowest to balance_conversion and limit to conversion asset type**
- **Split highest_in_out into balance_consumer and balance_hub**
- **Rename m.._energy_inter_rp to ..._over_clustered_year**
- **Rename storage constraints**
- **Rename constraint highest_in to capacity_incoming**
- **Rename constraint highest_out to capacity_outgoing and a copy to ramping_without_unit_commitment**
- **Rename units_on_and_outflows to ramping_with_unit_commitment**
Part of #642 
Closes #958
=> Rename and split some constraints to reflect Miro

src/constraints/create.jl, src/tmp.jl
This doesn't remove the active as proposed in #960, but it moves the check to earlier in the workflow - to the highest and lowest resolution.
Relates to #960
=> Move some of the active checks earlier in the workflow

docs/src/40-formulation.md, src/constraints/capacity.jl, src/constraints/create.jl, src/constraints/ramping-and-unit-commitment.jl, src/model-preparation.jl, src/structures.jl
- **Update capacity.jl to use attach and update tables related to it**
Part of #961
=> Update capacity.jl to use the new attach functions and update tables

src/constraints/create.jl, src/constraints/ramping-and-unit-commitment.jl, src/model-preparation.jl
Update ramp file with new attach_constraint, create new tables and change from groupby to loop over the entire table (to use the attach).
Depends on #963
Closes #964
=> Update ramping file with new attach_constraint and create new tables

src/constraints/storage.jl, src/variables/storage.jl
Use attach_constraint for balance_storage_rep_period.
Use attach_constraint for balance_storage_over_clustered_year.
Move variable bounds to src/variables/storage and clean up.
Closes #966
=> Use attach_constraint for src/constraints/storage.jl 

src/constraints/capacity.jl, src/create-model.jl, src/variables/flows.jl
- **Remove unnecessary accumulated_investment_limit expression**
- **Move lower bound of flow variable from capacity.jl to variable creation**
Related to #961
=> Remove unnecessary expression and move lower bound of flow variable from src/constraints/capacity.jl 

src/constraints/consumer.jl, src/create-model.jl, src/model-preparation.jl, src/structures.jl, src/utils.jl, test/test-case-studies.jl, test/test-pipeline.jl
=> Remove graph dependency from src/constraints/consumer.jl

src/constraints/capacity.jl, src/create-model.jl, src/utils.jl
- **Move part of capacity.jl to new profile**
- **Avoid using graph in src/constraints/capacity.jl**
Almost closes #947 - we have to remove `graph` from the profile used in the compact expression, which is not trivial, so best left for next year.
=> Remove most of graph from src/constraints/capacity.jl

src/constraints/ramping-and-unit-commitment.jl, src/create-model.jl, src/model-preparation.jl, src/structures.jl
Blocked by #978 and #979 
- Create a field coefficients in TulipaConstraint to allow attaching numeric columns to constraints without modifying the DuckDB table.
- Remove graph from src/constraints/ramping-and-unit-commitment.jl
Part of #942
=> Remove graph from src/constraints/ramping-and-unit-commitment.jl

src/constraints/storage.jl, src/create-model.jl
Blocked by #978, #979, #980 
- **Remove graph from src/constraints/storage.jl**
Part of #942 
Closes #955
=> Remove graph from src/constraints/storage.jl

.JuliaFormatter.toml, benchmark/profiling.jl, docs/src/91-developer.md, src/constraints/conversion.jl, src/constraints/energy.jl, src/constraints/group.jl, src/constraints/hub.jl, src/constraints/transport.jl, src/io.jl, src/run-scenario.jl, src/tmp.jl, src/variables/investments.jl, utils/csv-modifications.jl, utils/scripts/assets-data-revamp-2.jl, utils/scripts/assets-data-revamp.jl, utils/scripts/create-multiyear-data.jl, utils/scripts/prepare-for-multiyear.jl, utils/scripts/split-assets-year-data.jl, utils/scripts/split-graph-data.jl
=> Add explicit return to JuliaFormatter and docs

src/create-model.jl, src/io.jl, src/model-preparation.jl, src/utils.jl
Remove graph and representative_periods from add_expression_terms_rep_period_constraints.
Refactor the function to use the DuckDB tables instead of the DataFrames. 
This now uses DuckDB to compute the groups and the intersection. The type instability made the code a bit slower so to improve, we have to manually specify the types of some outputs with `::Type`. This made the code faster than it was before!
Part of #942
- ~~Docs were updated and workflow is passing~~
=> Remove need for representative_periods and graph in add_expression_terms_rep_period_constraints

test/runtests.jl, test/test-case-studies.jl, test/test-economic-parameters.jl, test/test-io.jl, test/test-model-parameters.jl, test/test-model.jl, test/test-options.jl, test/test-pipeline.jl
=> Add explicit 'using' to tests

Project.toml, src/constraints/storage.jl, src/create-model.jl, src/run-scenario.jl
=> Performance improvements

benchmark/benchmarks.jl, docs/src/20-tutorials.md, src/io.jl, src/run-scenario.jl, src/solve-model.jl, src/structures.jl, test/test-io.jl, test/test-pipeline.jl
- Update function to compute dual
- Create function to save solution and dual values to DuckDB connection
- Update `save_solution_to_file`
- Update tests
Closes #115 
Closes #818
=> Implement solution saving and exporting for refactored code

docs/src/10-how-to-use.md, docs/src/20-tutorials.md, docs/src/30-concepts.md, docs/src/40-formulation.md, docs/src/50-schemas.md, docs/src/60-structures.md, src/create-model.jl, src/solve-model.jl, src/structures.jl
~Blocked by #1000~
- Remove lower level usage of Tulipa to make it easier to update the internal until v1.0.0 is released.
- Add some notices indicating that the documentation is out-of-date (this only affects the latest build of the documentation, so we should make sure to update it before v0.11
- Fix small things to make the docs build
Closes #935
=> [docs]: prepare documentation for release 0.11.0

src/variables/create.jl
=> Fix sort in the query to keep linear index per asset in the storage constraint

src/model-preparation.jl
@datejada identified the warning for summation generating expressions, but I could not figure out where. @matbesancon helped figure out that `sum(coef * var)` also falls into that situation.
A more visually appealing solution would be changing that to `dot(coeffs, vars)`, but we would need to create the vectors for that, so we resort to `JuMP.add_to_expression!`.
Hopefully the benchmark should reveal some speed up. 
Related to #1014, missing warning.
=> Change sum(coef * var) to JuMP.add_to_expression

src/constraints/create.jl, src/constraints/ramping-and-unit-commitment.jl, src/create-model.jl, src/model-preparation.jl
This pull request involve renaming and removing certain constraints to better reflect their functionality.
Key changes include:
* Renamed `:ramping_with_unit_commitment` to `:min_output_flow_with_unit_commitment` in various functions and queries, since it is only use for that constraint. [[1]](diffhunk://#diff-69d05e81e3a0108b62f96ef5cc25a2d0ee158dd1003e7addead1510c792aa005L19-L22) [[2]](diffhunk://#diff-69d05e81e3a0108b62f96ef5cc25a2d0ee158dd1003e7addead1510c792aa005L210-R209) [[3]](diffhunk://#diff-9670152e2f4006a9ce07817b6dbca4ba8573bd1b4484e1fb6de8d48295f8d928L12-R12) [[4]](diffhunk://#diff-9670152e2f4006a9ce07817b6dbca4ba8573bd1b4484e1fb6de8d48295f8d928L35-R34) [[5]](diffhunk://#diff-9670152e2f4006a9ce07817b6dbca4ba8573bd1b4484e1fb6de8d48295f8d928L45-R43) …
=> Refactor names in the ramping constraints

src/structures.jl, src/variables/investments.jl
This was created for the strangle pattern during refactoring, and now it is not necessary anymore.
Related to #701
=> Remove variable lookup that was created only for the strangle pattern

src/run-scenario.jl
This pull request includes changes in the `run_scenario` function. The changes focus on improving the names in the timing and always saving the solution when using this function. Since this function is a wrapper of the individual steps, keeping the solution should be part of the steps while exporting should remain optional.
Also there is improvements in the docstring of the funtion.
=> Always saving the solution when using run scenario

src/create-model.jl, src/expressions/intersection.jl, src/model-preparation.jl, src/utils.jl, test/test-utils.jl
These are some improvements related to the creation of expressions attached to constraints.
There are three types of expressions attached to constraints:
- cons + var_flow on rep_period
- cons + var_flow over clustered year
- cons + asset-based var on rep_period (is_charging and units_on)
This PR makes it so the third one is used for both cases.
- Update is_charging expressions to use tables
- Create helper function `_create_group_table_if_not_exist`
- Create new file `src/expressions/intersection.jl` with a new function `attach_expression_on_constraints_grouping_variables`
- Use the new functions for both `is_charging` and `units_on`
- Pass workspace to attach_expressions_on_constraints...
Related to #701
=> Improvements to creating expressions attached to constraints

src/expressions/intersection.jl, src/model-preparation.jl, src/structures.jl
**Add type assertions in add_expression and attach_expression functions**
This should help make it a bit faster by making all three functions more type stable. All three functions are similarly typed now.
=> Add type assertions in add_expression and attach_expression functions

docs/src/40-formulation.md
Currently the docs render blank callout notes on this page https://tulipaenergy.github.io/TulipaEnergyModel.jl/stable/40-formulation/:
Notice the empty "Info" below in the following screenshot:
Admonition content should be indented to be rendered correctly: https://documenter.juliadocs.org/stable/showcase/#Admonitions
This PR indents the contents of all the `!!! tip` admonitions on the formulation page.
=> docs(formulation): Update formatting of tip admonition blocks by indenting the content in the raw markdown

src/constraints/capacity.jl, src/constraints/consumer.jl, src/constraints/create.jl, src/constraints/energy.jl, src/constraints/group.jl, src/constraints/ramping-and-unit-commitment.jl, src/constraints/storage.jl, src/constraints/transport.jl, src/expressions/intersection.jl, src/expressions/multi-year.jl, src/expressions/storage.jl, src/model-preparation.jl, src/objective.jl, src/solve-model.jl, src/utils.jl, src/variables/create.jl, src/variables/flows.jl, src/variables/storage.jl, test/test-utils.jl
Some cleaning in preparation to some SQL files. This changes all `index` to `id`, because `index` is a reserved keyword in some parts of SQL.
=> Rename index to id to prevent using sql keyword

test/test-case-studies.jl, test/test-io.jl
Windows line ending cause the tests to fail. The solution is to split the
strings so that it automatically removes the line endings.
Related to #1079
=> Fix Windows failure due to tests introduced in #1079

src/input-schemas.jl
Using `@__DIR__` to define a path is more robust.
Fixes a bug importing Tulipa
=> Use absolute path to include json file

benchmark/benchmarks.jl
The benchmark run is failing due to `var_flow` existing.
This happened after we changed to SQL in files, I believe, because we change
from "create or replace" to "create".
Bugfix
=> Create connection inside benchmark run because tables exist

src/TulipaEnergyModel.jl, src/data-validation.jl, src/io.jl, test/test-data-validation.jl
Create a data validation function to call various validation functions.
Call this data validation after initialising empty tables and before
creating the internal tables inside the create_internal_tables function.
Starting point for #461
Closes #1091
=> Implement data validation step with basic check for duplicate rows

src/data-validation.jl, src/input-schemas.jl, test/test-data-validation.jl
Add a validation step to check the schema's oneOf constraints.
I.e., loop over each table and their columns and find the ones
that have constraints of the type oneOf, and check if the
corresponding table in the connection have the correct specification.
Closes #1098
=> Validate schema's oneOf constraints

src/data-validation.jl, test/test-data-validation.jl, test/utils.jl
- **Make validation loop more maintainable**
- **Validate that the group foreign key has valid values**
- **Validate that any group listed in group_asset has matching assets**
Closes #1105
=> Validate group consistency in asset and group_asset tables

.github/workflows/CompareMPS.yml
The CompareMPS workflow should find older comments in the PR to replace, instead of creating new comments every time. (This is already done by the Benchmark workflow, I just missed it).
Add the link to the docs to the PR comment.
=> Update CompareMPS to not make multiple comments and link to docs

src/data-preparation.jl, src/solve-model.jl
This pull request includes a minor change to the error logging in the `save_solution!` function within the `src/solve-model.jl` file. The change ensures that the termination status, primal status, and dual status are converted to strings before being included in the error message.
* [`src/solve-model.jl`](diffhunk://#diff-f2bfe53eac044e75e0a0cb4abfea814584599e7da61f46bc87968bb1e1d72ee6L101-R101): Modified the error message in the `save_solution!` function to convert the statuses to strings for better readability.
=> Update error message when saving solution

src/input-schemas.json, src/io.jl
This pull request introduces a new table needed to define flow relationship constraints.
The changes include adding a new schema for `flows_relationships` in the input JSON and ensuring compatibility in the `io.jl` file.
* [`src/input-schemas.json`](diffhunk://#diff-25ff778353f0e7ecf765d8a10289d3b1e38faa2b8f3e4b8d2bd6f5f47b9f0c5fR652-R697): Added a new schema `flows_relationships` to define constraints between two flows.
* [`src/io.jl`](diffhunk://#diff-db104fa7ac6c3097a327fc13a1076a2f1dd30a49057cae4caebe58563a97030eR10): Updated the `tables_allowed_to_be_missing` list to include `flows_relationships` since this table is not always needed in the model.
Closes #1166
=> Add new table to define flows relationships

src/create-model.jl, src/sql/create-variables.sql, src/variables/create.jl, src/variables/power-flow.jl
Adding electricity angle variables based on asset resolution.
The variable is created if there is a connecting flow (incoming OR outgoing) that is transport and has dc_opf method.
Closes #1181
=> Add electricity angle variables

.github/workflows/CompareMPS.yml, docs/src/91-developer.md, utils/scripts/model-mps-compare.jl
If the files had different length, the script prints errors,
but was not returning errors. This returns the correct
exit flag.
Closes #1188
=> Fix CompareMPS when files differ in length

.github/workflows/CompareMPS.yml
This ensures that looks for earlier comments even if there was a failure.
Complements #1188
=> Always run find-comment in CompareMPS, whether it fails or not

src/data-preparation.jl, src/sql/create-merged-tables.sql, test/test-data-preparation.jl, test/utils.jl
This pull request refactors the `create_merged_tables!` function to simplify its implementation, introduces a new table for flow relationships, and expands test coverage for data preparation.
* Replaced inline SQL queries in `create_merged_tables!` with an external SQL file (`create-merged-tables.sql`) for better maintainability and readability. (`src/data-preparation.jl`, [[1]](diffhunk://#diff-da8a343a3066315da2c08dd913f31ea303b0d8fc2f40ef42efc055107cac889eL377-R377) [[2]](diffhunk://#diff-da8a343a3066315da2c08dd913f31ea303b0d8fc2f40ef42efc055107cac889eR386-R392) [[3]](diffhunk://#diff-a9f68e30d0a2783c2b4beec133bb8e5d0c53b05830e65026492592255d7a2434R1-R97)
* Added a new temporary table, `merged_flows_relationship`, to handle flow relationships, including creating and populating a …
=> Add new tables to calculate the lowest resolution for flows that have a flows relationship

src/data-preparation.jl, src/sql/create-merged-tables.sql, test/test-data-preparation.jl
The goal is to obtain the highest resolution between a flow and its connecting assets.
Used the same trick as in #1183, by creating a fake asset called (`from_asset`, `_`, `to_asset`).
This is a workaround and note by doing this, I'll need to split this asset later as I need the flow names.
Closes #1187
=> Create highest resolution table for flows and their connecting assets

src/sql/create-constraints.sql, src/sql/create-variables.sql, test/test-case-studies.jl
Ensure table creation is either 'create or replace' or drop the tables
before creating them. This ensures that they are overwritten.
Run the case studies tests once more running populate_with_defaults
before them to test two things:
- That populate_with_defaults does not change the solution
- That running twice does not raise errors because of existing structures.
Closes #1205
=> Run the case studies twice to ensure it doesn't raise an error

Project.toml, src/data-preparation.jl, src/input-schemas.json, test/test-defaults.jl
`populate_with_defaults` now creates a table using the schema and copies the data from the old tables enforcing the data types and defaults. Adds two tests, one for the type correction and one for filling NULLs.
Closes #1156
=> Make populate_with_defaults enforce schema (correct types and fill NULLs)

utils/scripts/model-mps-compare.jl
The MARKER INTORG/INTEND blocks denote blocks of integer variables.
If a model reorders the variables, there may be a different number of blocks
leading to a false negative.
Observed in PR #1291
=> Add generic functions to create variables with specifications per row

src/create-model.jl, src/variables/create.jl, src/variables/decommission.jl, src/variables/investments.jl, test/test-constraint-limit-decommission-compact-method.jl, test/test-variable-decommission.jl, test/test-variable-investment.jl, test/utils.jl
The main idea is to give more flexibility and readability to the investment and decommission variable creation by splitting their creation and addition to the model. Two new tests are added for the variable creation.
Closes #1272
- [N.A.] Docs were updated and workflow is passing
=> Refactor add investment variables

src/constraints/create.jl, src/constraints/vintage-flow.jl, src/create-model.jl, src/sql/create-constraints.sql, test/test-constraint-vintage-flow-sum.jl
This PR adds a vintage flow sum constraint for semi-compact method.
After splitting the flow variable into vintage-specific flow variables in #1280 (which applies only to the semi-compact method and outgoing flows—for example, separating CCGT-to-demand flows by CCGT commission year), this PR adds a summation constraint to ensure that the original flow variable is correctly linked with the vintage flow variables.
Please let me know if the intention is not clear :)
Closes #1290
=> Add vintage flow sum constraint

src/constraints/capacity.jl
This PR refactors the profile joins in the _append functions in capacity constraints.
Based on the discussion thread https://github.com/TulipaEnergy/TulipaEnergyModel.jl/pull/1301#discussion_r2242328674
=> Refactor profile joins in the _append functions in capacity constraints

src/data-validation.jl, src/objective.jl, test/inputs/Multi-year Investments/asset-commission.csv, test/inputs/Multi-year Investments/year-data.csv, test/test-data-validation.jl
There are two fixes:
- the JOIN in `t_objective_assets` has been changed: this means you would not need all milestone years in `asset_commission`, so it fixes #1309
- a validation has also been added to make sure the commission years between `asset_commission` and `asset_both` are consistent. That means if you have more commission_years in `asset_commission`, the validation will flag because this is not needed and is prone to errors. 
Closes #1309
=> Add validation to align data between `asset_commission` and `asset_both`

src/data-validation.jl, test/inputs/MIMO/asset.csv, test/test-data-validation.jl
Fix data validation of oneOf constraints by excluding NULL from valid types, as it is already checked in the correcy way.
Add a test using unit_commitment_method.
Fix MIMO data for use_binary_storage_method to be one of the valid oneOf values.
Closes #1321
=> Fix data validation of oneOf constraints and fix MIMO use_binary_storage_method column

src/data-validation.jl, test/test-data-validation.jl
This validation ensures when you use `semi-compact` method, the data is available in the `flow_commission` that corresponds to `asset_both`. This is needed to generate capacity constraints.
This validation is similar to #1313 which checks consistency between `asset_both` and `asset_commission` because the model needs to have the fixed costs from the corresponding `commission_year`.
Closes #1345
=> [Multi-year Part II] Validate consistency between `asset_both` and `flow_commission`
